### ISSUE TITLE
[question] Lua support in nginxinc/kubernetes-ingress with NGINX/Plus

### ISSUE THREAD

**Issue by cr8zi** [nginxinc/kubernetes-ingress#1002]
Hi,
Apologies in advance, is there a way to build nginxinc/kubernetes-ingress with Lua support? When we build kubernetes-ingress with NGINX, even Plus version, there is no ngx_http_lua_module.so in /usr/lib/nginx/modules, only modules listed bellow:
```
-rw-r--r-- 1 root root  24328 May 26 15:01 ngx_http_geoip_module-debug.so
-rw-r--r-- 1 root root  24328 May 26 15:01 ngx_http_geoip_module.so
-rw-r--r-- 1 root root  27568 May 26 15:01 ngx_http_image_filter_module-debug.so
-rw-r--r-- 1 root root  27568 May 26 15:01 ngx_http_image_filter_module.so
-rw-r--r-- 1 root root 632800 May 26 15:01 ngx_http_js_module-debug.so
-rw-r--r-- 1 root root 628704 May 26 15:01 ngx_http_js_module.so
-rw-r--r-- 1 root root  23400 May 26 15:01 ngx_http_xslt_filter_module-debug.so
-rw-r--r-- 1 root root  23400 May 26 15:01 ngx_http_xslt_filter_module.so
-rw-r--r-- 1 root root  19864 May 26 15:01 ngx_stream_geoip_module-debug.so
-rw-r--r-- 1 root root  19864 May 26 15:01 ngx_stream_geoip_module.so
-rw-r--r-- 1 root root 619232 May 26 15:01 ngx_stream_js_module-debug.so
-rw-r--r-- 1 root root 615136 May 26 15:01 ngx_stream_js_module.so
```
Can`t find any info about lua support in nginxinc/kubernetes-ingress, can somebody please clarify this.
Thanks for info,
Peter

**Comment by pleshakov** [comment]
Hi @cr8zi 

The Ingress Controller image for NGINX is based on the `nginx:1.19.0`, which doesn't include  any third-party modules like Lua.

If you would like to use Lua, you can modify the Dockerfile to install Lua. I think you can use the following the installation instructions -- https://github.com/openresty/lua-nginx-module#building-as-a-dynamic-module I recommend using [`DockerfileWithOpentracing`](https://github.com/nginxinc/kubernetes-ingress/blob/master/build/DockerfileWithOpentracing) as a reference, where we compile and install a third-party module (OpenTracing).

For Plus version, instead of compiling the module, you can install it using apt -- https://docs.nginx.com/nginx/admin-guide/dynamic-modules/lua/

Hope that helps
