### ISSUE TITLE
There is any doc of how to install it on baremetal?

### ISSUE THREAD

**Issue by stealthHat** [nginxinc/kubernetes-ingress#1026]
I was trying to install a nginx ingress contoller on my cluster baremetal, but when it comes to loadbalancer there is no doc for baremetal, only for cloud.

Its possible to install nginxinc/kubernets-ingress on baremental with loadbalancer? or I need to use kubernets/nginx-ingress?

**Comment by pleshakov** [comment]
Hi @stealthHat 

> Its possible to install nginxinc/kubernets-ingress on baremental with loadbalancer?

Service type LoadBalancer works with public/private clouds that provide a Load balancer as a service.  Although there are implementations for baremetal like https://metallb.universe.tf/

At the same time, there are other options for exposing Ingress Controller pods that works for baremetal:

You can expose the Ingress Controller pods via [NodePort service](https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/service/nodeport.yaml). And then use an external load balancer (software/hardware), so that it is configured to sit in front of the NodePort service.

Another option - deploy the Ingress Controller as a DaemonSet and use port mapping between IC ports 80,443 and host ports 80,443. Then, if your nodes have public IPs, you can connect to the IC using pubic IP of nodes on ports 80,443. Or you can put a load balancer in front of the nodes, similarly to the option above.

 Unfortunately, we don't have detailed instructions for those options.

**Comment by stealthHat** [comment]
Thanks for the quick answer, I guess I'll install the metallb in our cluster, have a nice day : )
