### ISSUE TITLE
setting "own" IP as real-IP when using tls-passthrough

### ISSUE THREAD

**Issue by cruwe** [nginxinc/kubernetes-ingress#1032]
Hi,

I observed that when using the tls-passthrough setup in conjunction with `hostIP: true`, the actual client IP does not get passed on to any backends.
Instead, what is passed as real-ip is the IP of the host nginxinc/kubernetes-ingress runs on.

I believe it is due to "double-passing" first
https://github.com/nginxinc/kubernetes-ingress/blob/05cf128de1c85626cfaca7593b2c806c31a23ff4/internal/configs/version1/nginx.tmpl#L197-L204
and then
https://github.com/nginxinc/kubernetes-ingress/blob/05cf128de1c85626cfaca7593b2c806c31a23ff4/internal/configs/version1/nginx.tmpl#L192-L195
to finally
https://github.com/nginxinc/kubernetes-ingress/blob/05cf128de1c85626cfaca7593b2c806c31a23ff4/internal/configs/version2/nginx.transportserver.tmpl#L14-L18

How would the controller need to be configured to avoid this issue?

**Comment by pleshakov** [comment]
Hi @cruwe, 

Unfortunately, NGINX doesn't preserve the client for TLS passthrough load balancing. That's  because NGINX cannot use the client IP to establish a TCP connection to the backend. For HTTP/HTTPs traffic, the IP is passed in the header `X-Real-IP`. However, for TCP connections (including TLS Passthrough), there is no such option. There is a way to pass it though -- use the [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). That's how the client IP is preserved between two NGINX stream servers when we do "double passing".

The TransportServer doesn't support PROXY protocol yet. However, you can try to add it - you need to add the `proxy_protocol on;` line to the server of the third template snippet that you referenced. However, you backend will need to support PROXY protocol as well.
