### ISSUE TITLE
real-ip configuration not applied to default server

### ISSUE THREAD

**Issue by svvac** [nginxinc/kubernetes-ingress#1072]
Configuration options like `real-ip-header`, `set-real-ip-from` and `real-ip-recursive` only get applied at the ingress level and not to the default server.

Since these are global options, they should be applicable there too.

Current workaround is redefining them in `http-snippets`.

On that note, these options are documented in the [Global options](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/), but don't appear in the [Ingress options](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/)

Proposed solution :
- The global options should end up in the `http` block
- Annotations for overriding these at the `server` level should be added/documented

**Comment by pleshakov** [comment]
Hi @svvac 

It is an omission that we don't set those directives in the default server. It makes sense to add them!

> The global options should end up in the http block
Annotations for overriding these at the server level should be added/documented

With the configmap/annotations, we don't necessary have this relationship that a configmap key sets a directive in the http block and  the corresponding annotation overrides the directive in the server/location block. 

So I wonder, if simply setting real-ip-header, set-real-ip-from and real-ip-recursive in the default server `server` block will do the job? 
Also, typically those directives apply to all Ingress resources, not individual ones (for example, when configuring proxy protocol https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/proxy-protocol), so that's why having annotation is not necessary. Could you clarify if you have a use case for those annotations?

**Comment by svvac** [comment]
> So I wonder, if simply setting real-ip-header, set-real-ip-from and real-ip-recursive in the default server server block will do the job?

Well, that's what I mostly care about indeed

> Also, typically those directives apply to all Ingress resources, not individual ones, so that's why having annotation is not necessary. Could you clarify if you have a use case for those annotations?

Not really. Skimming through the options code, I assumed those existed because the real ip params are defined in the ingress options struct, and not in the global options struct (though I ain't fluent in Go so maybe I'm missing something). Also duplicating them for each ingress rather than directly in the `http` block seemed to confirm that.

So in my opinion it'd be somewhat cleaner to move these in the global config (better reflecting the intent), but as I said I mostly care about having the default server using the right client IP address.

**Comment by magestic0100** [comment]
The IPv6 address is rooted to me **I AM HOST GOOGLE CLOUD AKA UNKNOWN NETWORK**  : **GOOGLE_CLOUD** IS SAFE AND IS AND ALWAYS WILL BE THE ROOTED FOUNDATION FOR THE HYBRID GLOBAL NETWORK. THE VIRTUAL WORLD HAS BEEN WAITING ON THE REST OF THE WORLD TO CATCH UP. I HAVE MY FILE ON THIS missing IPv6 ADDRESS FILE. FILED AS FOLLOWS IP Address 2600:1900:0:2601

:
