### ISSUE TITLE
nginx.ingress.kubernetes.io/server-snippet annotation not taking effect

### ISSUE THREAD

**Issue by tbudukh-vmware** [nginxinc/kubernetes-ingress#1093]
I have a API server where I want to block specific path from nginx kubernetes ingress. I have following ingress.yaml :
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-configuration-snippet
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/server-snippet: |
          location /base/path/v1/api/update {
              deny all;
              return 404;
            }
spec:
  rules:
    - http:
        paths:
          - path: /base/path(/|$)(.*)
            backend:
              serviceName: myApi
              servicePort: 8080
```

But I am still able to access `https://<server>/base/path/v1/api/update`  and get a response. Can somebody help ?

**Comment by lucacome** [comment]
Hi @tbudukh-vmware 

Based on your annotations I believe you're using the [community Ingress Controller](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md), that's a different project. Could you please check which version you're using?

Thanks

**Comment by Dean-Coakley** [comment]
Closing. 

`nginx.ingress.kubernetes.io/server-snippet` is an annotation of the [kubernetes community ingress controller](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md) and is not supported in this ingress controller.

**Comment by AivanF** [comment]
@lucacome @Dean-Coakley   I assume, the OP actually has ingress controller of _this_ project, and that's why the annotation has no effect. Also, this is the situation I just found myself – I had no idea about different NginX Ingress Controllers and could not understand why the annotations don't work...

So, I would reopen the issue and rephrase the Q to **What is the analogue for "server-snippet" K8s community Ingress annotation?** It is an important feature that allows to build tiny yet highly useful logical mechanics like smart redirection.

**Comment by AivanF** [comment]
After tiny googling I found the solution: simply replace `nginx.ingress.kubernetes.io/server-snippet` with `nginx.org/server-snippets`. [Here is more info on NginX Ingress Controller annotations](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/).
