### ISSUE TITLE
Unable to activate the proxy protocol feature starting from default configurations

### ISSUE THREAD

**Issue by martinlevesque** [nginxinc/kubernetes-ingress#1102]
**Describe the bug**

Starting from the default configurations, there seems to have no way to activate the proxy protocol feature in order to pass the real client IPs in headers to the application server.

**To Reproduce**
 - helm repo add nginx-stable https://helm.nginx.com/stable
 - helm install quickstart nginx-stable/nginx-ingress

 - Configure the NGINX configmap with proxy protocol in default namespace

```
apiVersion: v1
data:
  use-proxy-protocol: "true"
kind: ConfigMap
metadata:
  name: quickstart-nginx-ingress
```

 - Activate the proxy protocol of the load balancer, I am using digital ocean, see https://www.digitalocean.com/docs/kubernetes/how-to/configure-load-balancers/ :

`kubectl annotate service quickstart-nginx-ingress service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol=true
`

 - Then I configure a simple ingress, service, and deployment of echo server showing client IPs to client.mytesthostname.com

**Expected behavior**

Doing curl --header "Host: client.mytesthostname.com" http://[load-balancer-ip]/ should resolve the request and provide real IP in HTTP headers.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit

Latest

* Version of Kubernetes

1.18.6

* Kubernetes platform (e.g. Mini-kube or GCP)

Digital Ocean

* Using NGINX or NGINX Plus

NGINX

**Additional context**

Note that using the same procedure, *BUT* with the following repo works successfully:

```
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm install nginx-ingress stable/nginx-ingress
```

Is there a certain configuration which needs to be changed when using **helm repo add nginx-stable https://helm.nginx.com/stable**, or is there a certain issue I am missing?

Thanks

**Comment by Dean-Coakley** [comment]
Hi @martinlevesque 

Firstly, just because it's a common confusion. 
Please note that:
* `helm install nginx-ingress stable/nginx-ingress` installs https://github.com/kubernetes/ingress-nginx
* `helm install quickstart nginx-stable/nginx-ingress` installs https://github.com/nginxinc/kubernetes-ingress

These are two different implementation of an ingress controller. The supported annotations and configmap entries differ.


The equivalent configmap entry to [`use-proxy-protocol`](https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#source-ip-address) seems to be [`proxy-protocol`](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#listeners).

See the following example for more details:
https://github.com/nginxinc/kubernetes-ingress/tree/v1.8.0/examples/proxy-protocol

**Comment by martinlevesque** [comment]
Oh wow, thanks for pointing out this distinction. I understand they are different implementation, but it would have been great the have the same API/variables from my opinion.

**Comment by Dean-Coakley** [comment]
> it would have been great to throw an explicit error in my opinion - in this case I would have been notified clearly that use-proxy-protocol is not correct.

@martinlevesque I'm not sure why we haven't gotten around to adding a feature like that, I think it would be useful and it's a common misunderstanding.
