### ISSUE TITLE
nginx should auto-tune server_names_hash_bucket_size directive

### ISSUE THREAD

**Issue by coreyjohnston** [nginxinc/kubernetes-ingress#114]
When the nginx ingress controller tries to expose services which result in "long" hostnames that exceed default server_names_hash_bucket_size, nginx server dies with:

`Error when adding or updating ingress "kube-system-default-ingress": "Invalid nginx configuration detected, not reloading: Command nginx -t stdout: \"\"\nstderr: \"nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64\\nnginx: configuration file /etc/nginx/nginx.conf test failed\\n\"\nfinished with error: exit status 1"  `

The ingress controller should probably tune this nginx configuration knob automatically; as its aware of the length of the services' virtual host names and the max size of server_names_hash_bucket_size required. This would prevent manual directives being required in nginx's ConfigMap.

**Comment by pleshakov** [comment]
@coreyjohnston thanks for the suggestion! That is a convenient feature. However, we are trying to stay close to NGINX, not hiding/fixing its behavior.

**Comment by r4j4h** [comment]
I find manual directives in the ConfigMap to not be effective in fixing this error

**Comment by ash2k** [comment]
@pleshakov I'd argue that there is a big difference between nginx and nginx-based ingress controller. nginx is usually configured manually (i.e. has static configuration) and once works, left running. Correct value has to be specified because it will not start otherwise.
In case of ingress controller (i.e. dynamic configuration) what should a user do? Everyone will be bitten by this default behaviour and will eventually specify a huge number to "fix" the problem.
I'm not sure why it is tuneable in original nginx but in ingress controller this behaviour absolutely does not make any sense. User will create many Ingress objects, use long hostnames, etc and at some point in time things will just stop working.
Is there any reason why software cannot/should not do this tuning by itself? It does have all the necessary information, correct?
Please reconsider this feature request :)

p.s. if the value is specified explicitly it should use the value provided.

**Comment by pleshakov** [comment]
@ash2k 
thanks for the feedback. I agree that we should rethink it

**Comment by dotw** [comment]
Please rethink it. I'm still struggling with server_names_hash_bucket_size. I have configured the map but it doesn't work.

**Comment by lamLeX** [comment]
hi @pleshakov, is there any update on this issue?

**Comment by lamLeX** [comment]
Thanks for your reply. I managed to get it working with setting value in configmap, it would sufficient to unblock me for now.

**Comment by Dean-Coakley** [comment]
To resolve this issue we have increased the default value of `server_names_hash_bucket_size` from `64` to `256` in https://github.com/nginxinc/kubernetes-ingress/pull/678. 
The value can still be customised via ConfigMap if necessary

Closing.
