### ISSUE TITLE
TLS hanshake not working

### ISSUE THREAD

**Issue by JoseFMP** [nginxinc/kubernetes-ingress#1141]
NGINX Controllers in Kubernetes cluster, `nginx/nginx-ingress:1.7.0` and we just upgraded to 1.8.1, same issue.
Using Virtual Server.
I create a secret in the same namespace of the Virtual Server with two keys, one for the private key and another for the certificate. 
All as described in https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources

However, when trying to access NGINX from outside Kubernetes cluster, I get this error in Postman:
```
Error: write EPROTO 9235159532872:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 40
9235159532872:error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO:../../third_party/boringssl/src/ssl/handshake.cc:588:
```

If I try the same using cURL, I get this error:
```
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

If I disable TLS in NGINX, I can access the cluster normally and NGINX is forwarding everything as expected. So this issue happens only when I activate TLS.

My VirtualServer config:
![image](https://user-images.githubusercontent.com/24405049/93069730-360d4780-f6a8-11ea-938d-ce05ac24344f.png)

Secrets:
![image](https://user-images.githubusercontent.com/24405049/93070517-27736000-f6a9-11ea-8e6c-3edfa674a16d.png)
The private key is not protected by a passphrase.

I also captured the packets with Wireshark to see what's going on. Basically there is a TCP connection with a proper 3-way handshake. Nothing special there. After that I send to NGINX a TLS Client Hello with TLSv1.2. To which NGINX replied handshake failure without any obvious reason.

![image](https://user-images.githubusercontent.com/24405049/93084787-c6568700-f6be-11ea-991e-63e75ca6b4c0.png)

**Comment by JoseFMP** [comment]
For anyone experiencing the same issue, I got to fix it.
I added to NGINX Configuration these two:
```
 ssl-protocols: "TLSv1.1 TLSv1.2 TLSv1.3"
 ssl-prefer-server-ciphers: "True"
```

i.e. I ended up with a NGINX config file like this:
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  location-snippets: |
    add_header 'Access-Control-Allow-Origin' '*';
  ssl-protocols: "TLSv1.1 TLSv1.2 TLSv1.3"
  ssl-prefer-server-ciphers: "True"

And seems to work in 1.8.1 Kubernetes controller

**Comment by pleshakov** [comment]
Hi @JoseFMP 

Thanks for the detailed description!

This issue was due to a missing secret, right?  (as mentioned here https://github.com/nginxinc/kubernetes-ingress/issues/1142#issuecomment-692184508 )

If a TLS secret is missing, the IC will configure NGINX to break client attempts for establishing TLS connection for the affected Ingress or VirtualServer resources. 
However, for TLS v1.3, NGINX will not break the attempts. I suspect that after you configured `ssl-protocols: "TLSv1.1 TLSv1.2 TLSv1.3"`, you client was able to establish a TLS connection to NGINX using TLSv1.3.

We document that case here in the description of the secret field https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserver-tls  However, we don't document that for TLSv1.3. We will fix that!

**Comment by JoseFMP** [comment]
@pleshakov 
Interesting. It might be it was because of the missing secret. If I happen to double check it I will let you know.

I find it quite MISSLEADING: Why would NGINX refuse attempts to all TLS when the secret is missing (seems reasonable) BUT still accept connections for TLSv1.3 ?! i.e. What's so magic about TLSv1.3 that even if the secret is missing NGINX accepts the connections and will even provide a certificate on his own BUT for other versions of TLS won't?

**Comment by pleshakov** [comment]
> I find it quite MISSLEADING: Why would NGINX refuse attempts to all TLS when the secret is missing (seems reasonable) BUT still accept connections for TLSv1.3 ?! i.e. What's so magic about TLSv1.3 that even if the secret is missing NGINX accepts the connections and will even provide a certificate on his own BUT for other versions of TLS won't?

Indeed, it is misleading. this is due to how that behavior is implemented in NGINX config. 

When a secret is missing, the config looks like below:
```
        server_name example.com
        . . .
        ssl_certificate /etc/nginx/secrets/default;
        ssl_certificate_key /etc/nginx/secrets/default;
        ssl_ciphers NULL;
```

To make NGINX break client TLS connection, `ssl_ciphers` is set to `NULL`. In that case, it doesn't matter what cert we use in `ssl_certificate` and `ssl_certificate_key`. Because the `/etc/nginx/secrets/default` (which is the default certificate) is always present on the file system, we use that.

However, for TLS v1.3, which was added not too long ago, `ssl_ciphers NULL` doesn't work as for previous versions of TLS.  So that's why clients are able to connect using TLSv1.3.
