### ISSUE TITLE
NGINX Sending a wrong certificate signed by itself instead of the provided certificate

### ISSUE THREAD

**Issue by JoseFMP** [nginxinc/kubernetes-ingress#1142]
As the title says.

I have configured NGINX with VirtualServer. I have configured a secret with the private key and certificate as specified in the documentation.

NGINX starts and works fine, routing is working, load balancing all is good. HTTPS is now working BUT the certificate that NGINX provides is this:
![image](https://user-images.githubusercontent.com/24405049/93088411-0d934680-f6c4-11ea-93ea-62a532d5522d.png)

And NOT the certificate I have provided in the Kubernetes secret.
Obviously this is an issue because the certificate that NGINX is sending is not signed by an authority and the clients won't want to connect.

I do not see absolutely any log message in NGINX pod stating that is has an issue finding the certificate or that the certificate I provided is wrong or anything similar. So the config is:

![image](https://user-images.githubusercontent.com/24405049/93088609-5c40e080-f6c4-11ea-887d-777a5929cfb4.png)

And the secrets: 

![image](https://user-images.githubusercontent.com/24405049/93088694-737fce00-f6c4-11ea-96b9-3a10b7d74d3e.png)

This is 1.8.1

Questions: 

- Are the certificate + private key supposed to be encoded in base 64? I tried both not encoded and encoded, still not working.

- How to debug this?

**Comment by Dean-Coakley** [comment]
Hi @JoseFMP 

> Are the certificate + private key supposed to be encoded in base 64?

Yes. You can see an example of the format here: https://github.com/nginxinc/kubernetes-ingress/blob/v1.8.1/examples/complete-example/cafe-secret.yaml

My guess would be is that your VirtualServer is not in your `preview` namespace. Your Secret must be in the same namespace as your VirtualServer resource, this is an intentional security restriction. 
Ref "The secret must belong to the same namespace as the VirtualServer." (https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserver-tls)

> How to debug this?

To help debug the issue you can set `error-log-level` to `info` in order to see SSL debug.
https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#logging

**Comment by JoseFMP** [comment]
Thank you  @Dean-Coakley I can confirm both the VirtualServer and the secret are in the same namespace.
I set up the error log level to info, but I see nothing going on on SSL debug.

**Comment by JoseFMP** [comment]
@Dean-Coakley Sorry I got to see the error, indeed.
`nginx-ingress` says `Error trying to get the secret preview/nginx-certs-keys for VirtualServer api: error validating secret preview/nginx-certs-keys`

So yes it has a problem with the content of the secret. However I double checked both the certificate and the private key are correct, they match, not protected with passphrase. I tried both with base 64 encoding and non encoding.

Is there any way to get more information on why NGINX is `error validating` the secret?

**Comment by JoseFMP** [comment]
@Dean-Coakley 
So it is working now. It was a typo... I typed `tsl` instead of `tls` in one of the keys of the secret... LOL. Now is working.

FYI: The base 64 encoding is only required for the YAML manifest. Otherwise both the certificate and the key are stored without being base64-encoded.

**Comment by Dean-Coakley** [comment]
@JoseFMP Happy to hear you were able to resolve your issue!

That error message doesn't seem very helpful. Hopefully I can get around to improving it.
