### ISSUE TITLE
Error creating TemplateExecutor: open nginx.tmpl: no such file or directory.

### ISSUE THREAD

**Issue by shreeram3535** [nginxinc/kubernetes-ingress#1163]
I'm trying to build the nginx ingress controller by replacing image of  [this dockerfile](https://github.com/open-quantum-safe/oqs-demos/blob/master/nginx/Dockerfile) 
as base in the [nginx ingress controller dockerfile](https://github.com/nginxinc/kubernetes-ingress/blob/master/build/DockerfileForAlpine) instead of
FROM nginx:1.19.2-alpine AS base.

Now when I deploy this newly built ingress controller using manifest deployment on GKE.
It says following error:
Error creating TemplateExecutor: open nginx.tmpl: no such file or directory.

How should i add [this logic](https://github.com/open-quantum-safe/oqs-demos/blob/master/nginx/Dockerfile)  to the build system.

Please help me.
Thanks

**Comment by pleshakov** [comment]
Hi @shreeram3535 

If it's still relevant, I think the WORKDIR in https://github.com/open-quantum-safe/oqs-demos/blob/master/nginx/Dockerfile#L87 messes things up. The Ingress Controller Dockerfile expects WORKDIR to be "/". That's why the template file isn't copied to the correct location. That's why you got `Error creating TemplateExecutor: open nginx.tmpl: no such file or directory`
