### ISSUE TITLE
APPolicy - result incomplete

### ISSUE THREAD

**Issue by nergalex** [nginxinc/kubernetes-ingress#1223]
**Describe the bug**
Invocation of APPolicy creation generates an incomplete result: some External References are missing

**To Reproduce**
Find attached the playbook and the results. Please note the difference between `invocation` and `results `in job_25591_task_details-CREATE_external_WAF_policy.txt

**Expected behavior**
invocation = results

**Your environment**
* Version of the Ingress Controller: 1.9.0
* Version of Kubernetes: 1.19.0
* Kubernetes platform: AKS
* Using NGINX or NGINX Plus: NGINX Plus + App Protect

**Additional context**

[kubectl_describe_APPolicy.txt](https://github.com/nginxinc/kubernetes-ingress/files/5517946/kubectl_describe_APPolicy.txt)
[policy-external-generic.yaml.txt](https://github.com/nginxinc/kubernetes-ingress/files/5517947/policy-external-generic.yaml.txt)
[update_security.yaml.txt](https://github.com/nginxinc/kubernetes-ingress/files/5517948/update_security.yaml.txt)
[job_25591.txt](https://github.com/nginxinc/kubernetes-ingress/files/5517949/job_25591.txt)
[job_25591_task_details-CREATE_external_WAF_policy.txt](https://github.com/nginxinc/kubernetes-ingress/files/5517950/job_25591_task_details-CREATE_external_WAF_policy.txt)

**Comment by nergalex** [comment]
Understood: APPolicy does a syntax check and delete silently the uncompliant Keys.
Incorrect keys used were: `modificationReference `in spite of `modificationsReference`.
Regarding `evasionReference` or `evasionReference `, non works.

Feature request: could APPolicy generates an error when syntax/schema is not compliant?
Question: what is the good word for evasions Link Reference

**Comment by pleshakov** [comment]
Hi @nergalex 

If you use `kubectl` to create a policy with `modificationReference`, the kubectl command will fail:
```
kubectl apply -f test-policy.yaml
error: error validating "test-policy.yaml": error validating data: ValidationError(APPolicy.spec): unknown field "modificationReference" in com.f5.appprotect.v1beta1.APPolicy.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
That happens because kubectl perfroms validation based on the scheme that we ship with the policy CRD (https://github.com/nginxinc/kubernetes-ingress/blob/v1.9.0/deployments/common/ap-policy-definition.yaml#L17)

However, if you use some other client to create the policy, Kubernetes API will accept the resource, but silently prune that `modificationReference` field. We can simulate that with `--validate=false` to turn off kubectl validation:
```
kubectl apply -f test-policy.yaml --validate=false
appolicy.appprotect.f5.com/waf-policy-external-v created
```

As you can see, the resource was created and no error was returned. That is expected behavior and unfortunately we can't change it. Could you use `kubectl` in your environment?

Regarding `evasionReference`. Let me double check it with my colleagues.

**Comment by nergalex** [comment]
Thanks @pleshakov for your response
