### ISSUE TITLE
Exposing external dns

### ISSUE THREAD

**Issue by uabilkent** [nginxinc/kubernetes-ingress#126]
Hi,

I have a kops setup kind of similar with  @kris-nova kop 1.5.1 environment.

When i do the following steps from https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example

kubectl create -f nginx-ingress-rc.yaml
kubectl create -f tea-rc.yaml
kubectl create -f tea-svc.yaml
kubectl create -f coffee-rc.yaml
kubectl create -f coffee-svc.yaml (with clusterIP: None parameter as stated in your video https://www.youtube.com/watch?v=u-CE4c3fSfg 16:39)
kubectl create -f cafe-secret.yaml
kubectl create -f cafe-ingress.yaml

On "test the application" step 

kubectl get pods -o wide
kubectl get node my-kubernetes-nginx-node -o json | grep -A 2 ExternalIP

I can't get external IP it comes blank(i even added elastic IP to the node it self still no good)

And lastly

curl --resolve cafe.example.com:443:XXX.YYY.ZZZ.III https://my.k8s.domain.com/coffee --insecure 

I know that in order to resolve host i have to use Nginx plus but still i get "Failed to connect to 127.0.0.1 port 80: Connection refused" even if i try with localhost or 127.0.0.1 over ports 80, 443 or 8080

Do i need to expose my svc or am i missing something else?

Can you also help please @pleshakov ?

**Comment by pleshakov** [comment]
@uabilkent 

I suggest to first check that the controller is working properly. Could you enable extensive logging here -- https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/nginx-ingress-rc.yaml#L28 -- and check the controller logs by running: `$ kubectl logs <nginx-controller-pod> `
You should be able to see generated NGINX configuration, specifically a virtual server that listens on ports 80 and 443. If it wasn't generated, you wouldn't be able to connect to those ports from the host and you'd get connection refused, as in your case.

The video is a little outdated: there is no need to set ClusterIP:None in order to use the Plus controller, as it no longer relies on DNS. Also, the cafe example works the same way for NGINX and NGINX Plus controllers.

Regarding the external IP problem.  It might be the problem of the kops kubernetes, if it doesn't set external IPs as properties of nodes. 

Alternatively to exposing ports on Kubernetes nodes to access the Ingress controller, you can expose the controller as a service behind a load balancer -- https://kubernetes.io/docs/user-guide/services/#type-loadbalancer

**Comment by uabilkent** [comment]
Thank you very very much for your answer @pleshakov but i still get same error as before

:~/nginx-ingress$ kubectl get node ip-172-9-4-137.eu-central-1.compute.internal -o json | grep -A 2 ExternalIP
                "type": "ExternalIP"
            },             <------ **There should be an external address here am i wrong?** 
            {

Also externsive logging shows no error and gives 

.
.
.
controller.go:190] Endpoints kube-controller-manager changed, syncing
utils.go:78] Syncing kube-system/kube-controller-manager
controller.go:323] Syncing endpoints kube-system/kube-controller-manager
controller.go:190] Endpoints kube-scheduler changed, syncing
utils.go:78] Syncing kube-system/kube-scheduler
controller.go:323] Syncing endpoints kube-system/kube-scheduler

And still getting 
curl: (7) Failed to connect to cafe.example.com port 443: Connection refused

I wonder what am i missing

**Comment by pleshakov** [comment]
>}, <------ There should be an external address here am i wrong?

Yes. Also, running this command `kubectl get nodes -o wide` shows external IPs of each node. However, this depends on a Kubernetes deployment. Do VM machines in your deployment have public IP assigned by AWS?

The extensive logging should have shown the generated NGINX configuration for the cafe-ingress.yaml file? Were you able to see that? 

Also, could you connect to the pod by running `kubectl exec -it <nginx-plus-pod> -- bash`, install curl `apt-get update && apt-get install curl` and try to curl to NGINX from within the pod?

**Comment by uabilkent** [comment]
Yes, i did see the Nginx configuration. 

From pod i can curl to port 80 and 443

I have 2 nodes(slaves) and 1 master, slaves does have external-ip addresses but not the master (as output from get node command) is it possible that master failed to assign it self an ip address?

**Comment by pleshakov** [comment]
ok, since you are able to connect to NGINX from the pod, I suggest to try to use the `hostNetwork` option. 
```yaml
...
 spec:
      hostNetwork: true
      containers:
      - image: nginxdemos/nginx-ingress:0.7.0
...
```
The problem might be similar to this https://github.com/nginxinc/kubernetes-ingress/issues/107

> I have 2 nodes(slaves) and 1 master, slaves does have external-ip addresses but not the master (as output from get node command) is it possible that master failed to assign it self an ip address?

I suggest to ask this questions in the kop repo https://github.com/kubernetes/kops

**Comment by uabilkent** [comment]
Thank you so much, now i at least can get a bad request page from Nginx, it is something. 

Thank you very much i will continue to try to make this work
