### ISSUE TITLE
Error creating TemplateExecutor: open nginx-plus.tmpl: no such file or directory

### ISSUE THREAD

**Issue by jnunham** [nginxinc/kubernetes-ingress#1410]
I'm trying to deploy nginx-plus following the instructions at [https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/](https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/). 

I'm specifically trying to use the `DockerfileWithOpentracingForPlus` Dockerfile. I can build the image successfully and push it to my ACR with the following command: `make Dockerfile=DockerfileWithOpentracingForPlus PREFIX=[removed].azurecr.io/nginx-plus-ingress`

However, when the pods attempt to start, they go in to CrashLoopBackOff with the following error in the logs: `Error creating TemplateExecutor: open nginx-plus.tmpl: no such file or directory`.

I'm then deploying it with helm:
```
helm upgrade --install nginx-plus nginx-stable/nginx-ingress \
    --set controller.image.repository=[removed] \
    --set controller.nginxplus=true \
    --namespace ingress-nginx \
    --values values2.yaml'
```

With the contents of values2.yaml being:
```
controller:

  nginxplus: true
  image.repository: "[removed]"
```

I'm not sure what I'm doing wrong, as I'm following the directions provided. Any assistance would be greatly appreciated.

**Comment by Dean-Coakley** [comment]
HI @jnunham 

From a quick test it seems to me that
```yaml
image.repository: "[removed]"
```

is not valid syntax for helm. I changed it to
```yaml
image:
  repository: "[removed]"
```

Example:
```sh
$ helm template deployments/helm-chart -f deployments/helm-chart/test-values.yaml| grep image
      - image: "[removed]:edge"
        imagePullPolicy: "IfNotPresent"


$ vim deployments/helm-chart/valu.yaml
$ helm template deployments/helm-chart -f deployments/helm-chart/test-values.yaml | grep image
      - image: "nginx/nginx-ingress:edge"
        imagePullPolicy: "IfNotPresent"
 ```
 
 So then you receive that error because the Ingress Controller tries to start with NGINX Plus enabled but references a OSS docker image.

**Comment by jnunham** [comment]
Hi @Dean-Coakley,

Thanks for the response. I've updated that in the values file, however I am still seeing the same error. Here is the new layout of that section for reference:

```
controller:

  nginxplus: true
  image:
    repository: "foobar"
```

**Comment by Dean-Coakley** [comment]
@jnunham I recommend first inspecting the generated deployment/daemonset manifest. Ensure the repository is getting set correctly.

If the registry is set correctly: 
* It must be pulling the correct image reference, but it must've been built incorrectly. You can validate by running `kubectl exec -it [ingress controller pod] -- ls | grep .tmpl` and see if `nginx-plus.tmpl` is present. If `nginx.tmpl` is present, this validates the image is not correct. 
* Note if you ran your make command from the original post without first checking out to the `release-1.10` branch, this would build `nginx-plus-ingress:edge` whereas the chart would generate a manifest with: `nginx-plus-ingress:1.10`.


If the registry is not set correctly: 
* Try `--set controller.image.repository=[removed]` as the final part of your helm upgrade command to ensure nothing in values is overriding the value. Otherwise, you could try apply the results of `helm template` with `kubectl`.

**Comment by jnunham** [comment]
@Dean-Coakley  I ended up opening a case with F5. They recommended that I add the following to my values.yaml file under the image section: `pullPolicy: Always`. As soon as I did that, the pods started up. I'm not sure why this suddenly started working, I imagine something must've gotten cached that wasn't the right image? Regardless, this got it working for me.
