### ISSUE TITLE
ProxyBuffering is always on

### ISSUE THREAD

**Issue by woopstar** [nginxinc/kubernetes-ingress#148]
In the `config.go` file in the `nginx` folder, the default value for `ProxyBuffering` is `true`.

And in the template the buffering is set as following:
`proxy_buffering {{if $location.ProxyBuffering}}on{{else}}off{{end}};`

So setting the option in the config map results in `on`, but not setting it also results in `on`.

**Comment by woopstar** [comment]
I did not want to do a pull-request setting the default to false for this option as I think its not up to me to decide. There must be a good reason to why this is default on?

**Comment by pleshakov** [comment]
> So setting the option in the config map results in on, but not setting it also results in on.

What do you mean by not setting the option? `proxy-buffering: 'False'`? In this case, you should get `proxy_buffering off;` in the config.


> I did not want to do a pull-request setting the default to false for this option as I think its not up to me to decide. There must be a good reason to why this is default on?

Buffering helps to optimize performance with slow clients, which can waste proxied server time if the response is passed from NGINX to the client synchronously. However, when buffering is enabled NGINX allows the proxied server to process responses quickly, while NGINX stores the responses for as much time as the clients need to download them.
In general, the network between NGINX and backends is fast and reliable comparing with the network between clients and NGINX. So that clients are slow.

**Comment by woopstar** [comment]
You are so right. I was so tired yesterday when doing this. We can close this issue ;)
