### ISSUE TITLE
How to setup case insensitive paths with mergeable ingress?

### ISSUE THREAD

**Issue by riesbl01** [nginxinc/kubernetes-ingress#1664]
I am currently deploying nginx with mergeable ingress. The annotations I am deploying are: 
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: <release name>
    meta.helm.sh/release-namespace: <release_namespace>
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.org/mergeable-ingress-type: minion
    nginx.org/rewrites: serviceName=<service_name> rewrite=/
    nginx.org/ssl-services: <service_name>

So you can see I am using the master/minion annotation which is why I think there may not be support for case insensitivity for this type of ingress yet. So my question is, does anyone know of a way to support case insensitive paths with nginx mergeable ingress?

**Comment by jasonwilliams14** [comment]
Hi @riesbl01 
Thank you for stopping by.

There are a couple things I noticed in your request.
This particular annotation:
```
 nginx.ingress.kubernetes.io/use-regex: 'true'
```
Is part of a different Ingress project located here:
[NGINX Ingress](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#use-regex)
That particular annotation will not work with our projects Ingress controller.

In order to use regex with our Ingress controller, you will want to use our CRD capabilities using virtualServer/virtualServerroute:
[NGINX Ingress regex](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#) 
Since you are using master/minion, you can easily migrate to using VS/VSR and add much more functionality including 'regex' capabilities. 
HTH!

**Comment by riesbl01** [comment]
Solve by moving to Virtual Server. Closing issue.
