### ISSUE TITLE
Errors when using examples

### ISSUE THREAD

**Issue by prefer** [nginxinc/kubernetes-ingress#22]
Hello!
I'm trying to use examples.
When I've executed:
`kubectl create -f nginx-ingress-rc.yaml  ` 
I've saw in the docker:
```
[root@node1 ~]# docker logs a4dd854833f7
E0429 09:33:03.138743       1 helper.go:367] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
F0429 09:33:03.158596       1 main.go:57] Failed to get kube-dns service, err: Get https://10.254.0.1:443/api/v1/namespaces/kube-system/services/kube-dns: x509: certificate signed by unknown authority
```
k8s version: v1.2.3.

Thanks for your help!

**Comment by pleshakov** [comment]
Hi,

It fails because the k8s API client library couldn't found the certificates that are used in commucations with the k8s API server. If you run  `$ kubectl get secrets --namespace=kube-system` , you should be able to see default-token secret of the kubernetes.io/service-account-token TYPE.
These certificates are accessible from within a container through a mounted folder. I'm not sure why they're not present in your case.

How did you deploy Kubernetes?

**Comment by prefer** [comment]
Thanks for the tip! I was need to [prepare certs](http://kubernetes.io/docs/getting-started-guides/scratch/#preparing-certs) and add it in the apiserver.
We build our rpm package with k8s, there was not function for generating certs.
