### ISSUE TITLE
container Image vulnerabilities

### ISSUE THREAD

**Issue by rjrhaverkamp** [nginxinc/kubernetes-ingress#232]
Hi @pleshakov 

we make use of multiple NGINX plus instances in google kubernetes engine. Google recently added a [vulnerability scanner](https://cloud.google.com/container-registry/docs/vulnerability-scanning) to its image registry.

As you can see in the image below it detected 93 vulnerabilities of which 6 Critical, 19 High, 50 Medium, 6 Low and 12 Unknown in severity.

![image](https://i.imgur.com/zPx16p2.png)

I'm not sure if this affects the running NGINX process at all, but I think this should be fixed.
If I can be of any assistance, let me know.

~ Rob

**Comment by pleshakov** [comment]
@rjrhaverkamp 

Please rebuild your image to use the latest version of  `ubuntu:16:04` to make sure you have the latest version of all packages. If you're using the `Makefile` to build the Ingress controller image, we've added the `DOCKER_BUILD_OPTIONS`, so that you can run `$make DOCKER_BUILD_OPTIONS=--pull ...` to make sure that the docker build command will pull the latest version of the base image `ubuntu:16:04`. This way we can minimize the number of vulnerabilities.

As an NGINX Plus customer you can get support directly from us. If you prefer, you can create a support ticket, using the email addresses (for you and for NGINX engineering) in your support contract to send and receive support case information.

**Comment by thresheek** [comment]
Another option would be to move to a slimmer version of a base distro - e.g. debian:stretch-slim - which hopefully will have less of an attack surface.  Also removing everything install during the build of the image is a good idea to minimize that issue as well.  Unfortunately there is no good way other than rebuilding an image every once in a while.

**Comment by pleshakov** [comment]
@rjrhaverkamp please check https://github.com/nginxinc/kubernetes-ingress/blob/plus-dockerfiles/nginx-controller/DockerfileForPlusStretch for a DockerFile for `debian:stretch-slim` Soon we will make it as the default DockerFileForPlus instead of the Ubuntu 16.04 -based one.

**Comment by rjrhaverkamp** [comment]
The first image is a scan of the Ubuntu 16:04 image(with the latest version pulled). The second image is the Debian Stretch image. It's a huge improvement. Thanks! 👍 

<img width="1137" alt="screen shot 2018-01-30 at 13 36 16" src="https://user-images.githubusercontent.com/20729073/35566718-a6e9b724-05c2-11e8-9c2c-f586eb70e227.png">
<img width="1161" alt="screen shot 2018-01-30 at 13 35 42" src="https://user-images.githubusercontent.com/20729073/35566719-a704a4a8-05c2-11e8-99c1-fc50b8fa6bdc.png">

**Comment by pleshakov** [comment]
the image for Plus now uses Debian Stretch -- https://github.com/nginxinc/kubernetes-ingress/commit/0dafb34fa491edf75eb651e400f9de34ef8ad985
