### ISSUE TITLE
Nginx Ingress not defaulting to use wildcard/default TLS certificate

### ISSUE THREAD

**Issue by pedroosorio** [nginxinc/kubernetes-ingress#2409]
I've deployed some services that will trigger cert-manager to generate a certificate for it, that Nginx will use. Due to some third-party reason, cert-manager didn't issue a particular certificate.

My surprise comes when I  see that Nginx is not serving the TLS certificate for that server (expected, does not exist), neither the "default" (wildcard-tls-secret, I assume) one.Upon certificate existence, everything returns to normal.

1. Deploy nginx with a wildcard certificate
2. Deploy an ingress with a specific certificate that does not exist
2. Verify that ssl_certificate and ssl_certificate_key are not present in the ingress's conf file

Am I expecting the wrong thing when I set '-wildcard-tls-secret' ? How can we achieve such behavior when Nginx starts serving the wildcard certificate when the certificate its looking for is missing ?

Environment:
* nginx/nginx-ingress:2.1.0
* Kubernetes 1.19.6 cluster
* Self Hosted in AWS
* Using NGINX

**Comment by brianehlert** [comment]
I believe you are attempting to perform what is shown in the example here: https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/wildcard-tls-certificate

**Comment by razrd** [comment]
Well sink me, I am facing this same issue., my environment is on AWS.

CLB (TCP) TLS Termination-> NGINX IC -> VS (Custom Resource/Policy) -> API Service -> API Deployment (Replicaset).
All the configuration was done using manifests.

What I really wanted was to TLS terminate at the  NGINX IC but  I just wanted to test the TLS termination at the CLB.

1. CLB is setup with TCP health check,  HTTPS 443 -> HTTP 80 termination (forwards the requests to app selector NGINX IC at 80).  The nginx conf is not using the proxy_protocol: TRUE  due to TLS termination at CLB.
2. NGINX is running with  enable custom resource (using Virtual server/route), enable snippets (Rate policy), uses the --wildcard-tls-cert option in the args with the secrets.
3. Virtual server is setup  with tls: set to blank ""   and host on virtual server is set to dev.domain.com (already have an AWS public domain in the same name - dev.domain.com)
TLS secrets is self signed for CN *.dev.domain.com (tls.cert , tls.key on the kubernetes secrets)
4. Route53 points to the CNAME of the CLB e.g.,  api.dev.domain.com 

When I send post requests to the  api.dev.domain.com/path1 (path1 is configured on the Virtual Server route to foward to thes ervice which in turn forwards to the actual pod), nothing happens as the host: "api.dev.domain.com" is set by the CLB on the header and  NGINC IC responds back with  / (default path) - 404  so my default is left at  / { 404 } on the nginx.conf

Now when I set the  host manually using when sending the HTTPS call,  host: "dev.domain.com"  as per the Virtual server, the IC forwards the request to the api service which points at the api pod and I get a response.

I was assuming that the  wildcard-tls-certificate parameter verified  the host at the virtualserver/route but this is not happening or  maybe my expectation is wrong.  Any enlightnment will be helpful.

So one minor detail -> I  did not enable the proxy_protocol on the  nginx.conf

 
CLB (TCP healthcheck, HTTPS to HTTP listener) TLS Termination-> NGINX IC (only using 80 port) -> VS (Custom Resource/Policy) set to  host: dev.domain.com (valid domain in AWS public hosted zone) -> API Service (80 to 10200) -> API Deployment (Replicaset target: 10200 HTTP).

**Comment by pedroosorio** [comment]
> I believe you are attempting to perform what is shown in the example here: https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/wildcard-tls-certificate

Hey, thanks for reaching out. Not really what I want to do. I have an ingress with a specific certificate. That certificate happens to be unavailable, so the wildcard should be used. This was the behavior in earlier versions ( helm chart v0.9.1 ). I did not see any documentation on this, so i think it is a regression. I implemented a fix in the ingress template but I would rather see this fixed

**Comment by ganapathi-s** [comment]
Will it support multiple wild card certificate ? Is there any workaround to use multiple wild card cert  in single ingress controller?

**Comment by pedroosorio** [comment]
> Will it support multiple wild card certificate ? Is there any workaround to use multiple wild card cert in single ingress controller?

Out of the box it does not. You can have multiple certs in a single ingress controller, but not multiple "wildcard" certificates, in the sense of the nginx setting. This is a regression to previous behavior.
