### ISSUE TITLE
I found that the default-server-return parameter in ConfigMap does not take effect

### ISSUE THREAD

**Issue by orangeops** [nginxinc/kubernetes-ingress#3103]
**Describe the bug**
On this page I found that the default-server-return parameter in ConfigMap does not take effect

“https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/”

**To Reproduce**
my config file

 kubectl get cm  -n nginx-ingress -o yaml nginx-config                                                       
apiVersion: v1                                                                                                                           
data:                                                                                                                                    
  default-server-return: 404 https://miodev.cqringpark.com/admin/404/index.html                                                          
  redirect-to-https: "True"                                                                                                              
  ssl-redirect: "True"                                                                                                                   
kind: ConfigMap 

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/52404640/192465715-60e0e492-cbdf-43c4-ac81-33c56919cb62.png">
****

**Expected behavior**

When I visit https://miodev.cqringpark.com/admin/abcdefg I can redirect to https://miodev.cqringpark.com/admin/404/index.html

But now when the page 404 appears, the default nginx 404 page appears, and it does not jump to the friendly page defined by myself.

**Comment by ciarams87** [comment]
Hi @orangeops 

In order to redirect to another page, you need to specify one of the redirect HTTP status codes along with a redirect URL. A 404 status code does not support a redirect URL. Please see the [return directive documentation](https://nginx.org/en/docs/http/ngx_http_rewrite_module.html?&_ga=2.40012196.780120050.1664203867-712280310.1664203867#return):

> it is possible to specify either a redirect URL (for codes 301, 302, 303, 307, and 308) or the response body text (for other codes)

So in your case, you could try `default-server-return: 302 https://miodev.cqringpark.com/admin/404/index.html`

Please let me know if you any further questions.
Thanks,
Ciara
