### ISSUE TITLE
HSTS Missing From HTTPS Server

### ISSUE THREAD

**Issue by Xuezenghuigithub** [nginxinc/kubernetes-ingress#3144]
**Describe the bug**
After scanning the results of the Tenable, we found this vulnerability in our nginx-ingress-controler: `HSTS Missing From HTTPS Server`, and I tried more than one way and couldn't fix it.

**To Reproduce**
1. Open browser and visit nginx-ingress IP
2. View `404 Not Found by nginx/1.21.5`, Cannot be redirected to https

<img width="1972" alt="image" src="https://user-images.githubusercontent.com/40421053/195494878-c5870a41-5ab5-4b8f-8ce4-b67f8bdaaa71.png">

3. add  hsts config [reference](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/)--doesn't work

4. delete nginx-ingress service's 80 Listening Port--rules doesn't work, deployment 404

<img width="2328" alt="image" src="https://user-images.githubusercontent.com/40421053/195495371-162c0fcf-6bfd-4b1a-be6b-1bf49c102710.png">

5. add IP to domain name's proxy--rules doesn't work, deployment 404

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/40421053/195495478-56040ce4-9d9d-4ef7-900a-03752ce76e50.png">

**Expected behavior**

When I access the ingress IP, I cannot access or can be redirected to the https site.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
nginx/nginx-ingress:2.1.0

* Version of Kubernetes
AKS v1.22.6

* Kubernetes platform (e.g. Mini-kube or GCP)
Azure

* Using NGINX or NGINX Plus
NGINX

**Additional context**
null

**Comment by brianehlert** [comment]
There are a few things happening here:

NGINX by default does hostname matching.  Any request that does not match the configured hostname will be tossed away (result in 404).
Therefore, if you configured foo.com as the hostname and you browse to 1.2.3.4 instead - those hostnames do not match.
I suggest you modify the hosts file of your client to resolve the hostname to the private IP of the deployment to test.

You are using some annotations that are not supported by this project:

- nginx.ingress.kubernetes.io/rewrite-target
- nginx.ingress.kubernetes.io/proxy-body-size
- nginx.ingress.kubernetes.io/use-regex
- nginx.org/enable-http
- nginx.org/proxy-request-buffering

These will be ignored.  More here: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/

Since you are using an Ingress resource and not a VirtualServer resource you will want to focus on these annotations for HSTS: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#:~:text=True-,nginx.org/hsts,-hsts

I would honestly suggest you take a look at the VirtualServer resource.  It provides greater flexibility and control, it aligns with where Gateway API is heading, has been proven for multiple years: https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/

**Comment by brianehlert** [comment]
Rereading your question....
Are you asking how to not listen on port 80 at all?

It is possible for NGINX to listen on port 80 but not expose port 80 by not exposing port 80 for the service using the definition of the Service object for the ingress controller.  Then there is nothing to respond on port 80 for the cluster and also a loadbalancer is not configured for the port.

The other option is to redirect port 80 to 443 using the ingress controller (or even the loadbalancer).  To enforce TLS.

I think it really comes down to what you are trying to accomplish.

**Comment by Xuezenghuigithub** [comment]
thanks a lot, I'll try it...
