### ISSUE TITLE
Unable to read configmap & secrets when deploying pods using kube manifest, its deployed in AKS (private cluster)

### ISSUE THREAD

**Issue by Naveen-LinuxAwsguy** [nginxinc/kubernetes-ingress#3399]
[I am trying to configure Nginx ingress controller on AKS without HELM, I am using manifest files from official nginx website](https://stackoverflow.com/questions/74875261/i-am-trying-to-configure-nginx-ingress-controller-on-aks-without-helm-i-am-usin)
![kymRd](https://user-images.githubusercontent.com/66349740/210078129-b78e806b-894c-4241-b3d2-05dfa248054f.png)

**Comment by vepatel** [comment]
Hi @Naveen-LinuxAwsguy, can you please provide the information below for us to have a better understanding?

**To Reproduce**
Steps to reproduce the behavior:
1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
* Version of Kubernetes
* Kubernetes platform (e.g. Mini-kube or GCP)
* Using NGINX or NGINX Plus


**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vepatel** [comment]
closing this as per https://github.com/nginxinc/kubernetes-ingress/blob/main/ISSUE_LIFECYCLE.md
