### ISSUE TITLE
Switch ServiceAccount to token volume projection instead of automounting

### ISSUE THREAD

**Issue by sigv** [nginxinc/kubernetes-ingress#3562]
**Is your feature request related to a problem? Please describe.**

From a security posture perspective, auto-mounting Service Account tokens is not preferrable.

Looking at documentation, there may be protections in place starting with K8s v1.26 for how the token gets invalidated, but it's a clunky "easy mode" approach where K8s is expected to auto-magically handle the token.

**Describe the solution you'd like**

[ServiceAccount token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection) feature (stable from K8s v1.20) is current preferred approach for obtaining Service Account token. It provides more flexibility and security with the token auto-rotating, and additionally being invalidated when the linked Pod is removed.

A projected volume needs to be configured with `serviceAccountToken` type, and explicitly mounted inside of the Ingress Controller container spec.

**Describe alternatives you've considered**

There are no actively supported other approaches. Current implementation with auto-mounting is the alternative, but provides less flexibility.

**Additional context**

**Comment by brianehlert** [comment]
What I am missing that would be super helpful (since you have gone deep on this) is a quick understanding of how the new methodology is superior to the existing.
Or if it was uncovered that the current method is or will be deprecated.

If you could short cut this knowledge discovery for us and provide some added depth, it would be really helpful.
