### ISSUE TITLE
type: 'Warning' reason: 'Rejected' spec.rules[0].host: Required value

### ISSUE THREAD

**Issue by lin423497786** [nginxinc/kubernetes-ingress#4211]
type: 'Warning' reason: 'Rejected' spec.rules[0].host: Required value， Why do you have to set host, don't you set it?

**Comment by brianehlert** [comment]
You must define the host (DNS name) in the Ingress or VirtualServer object when you define it, so that NGINX will know what hostname to match on for routing the traffic.
That is why you have a schema validation error.

For example: company.com or www.company.com or foo.company.com
these could all be handled using a single Ingress / VirtualServer object and a wildcard domain (host name) or defined individually and thus have different individual rules.

Without you defining those things, we have no idea of your intentions.

Also, NGINX by default does host name matching.  Any traffic that does not match the known host names is ignored.

**Comment by vepatel** [comment]
Please refer to https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/#restrictions for more information on Ingress spec.

> When defining an Ingress resource, the host field is required.

**Comment by QuinnBast** [comment]
I know this is old, but why is this a requirement?

We are using air-gapped cluster deployments and a lot of TLS signing issuers (like cert-manager) use this field to provide TLS certs. However, in air-gapped environments we can't do DNS resolution and we need to use self-signed certs which require using a floating IP address for the cluster. However, not being able to input an IP address for this field is very limiting for air-gapped on-prem deployments.

I'd love to be able to just put our cluster's IP address in here for the `host` field so that our TLS certs can be generated properly...

The workaround is crappy - tell all users of the k8s cluster to add an entry to their `/etc/hosts`... Not ideal.
