### ISSUE TITLE
Allow an HPA `behavior` object to be passed

### ISSUE THREAD

**Issue by saedx1** [nginxinc/kubernetes-ingress#4392]
**Is your feature request related to a problem? Please describe.**
Nginx ingress controller scales up very quickly to the maximum when it needs to reload configs. The flapping is huge, and for us, it scales up to the `maxReplicas` (25) in a matter of minutes when configs change (config reloads cause a CPU and Mem spike). Allowing for custom behavior to [avoid flapping](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior) is suggested by the Kubernetes docs and has yielded better results for us and more stable and reasonable scaling.

**Describe the solution you'd like**
I created a pull request (#4391) to allow passing the `spec.behavior` object to the `HorizontalPodAutoscaler` template. Very basic; defines a value in the values file that defaults to empty, and references it in the `templates/controller.hpa.yaml` as is.

**Describe alternatives you've considered**
- Pulling the chart and modifying it locally; or
- Using helm `--post-renderer`
Both are hacky and require custom code on our end that is not guaranteed to work with updated versions.

**Comment by saedx1** [comment]
Can we get any traction on this? It is a very simple change.

**Comment by brianehlert** [comment]
How well does this work for you?

I am asking because we normally recommend customers simply increase their limits to accommodate the resource spikes that come with reloads.  We actually consider it more efficient to increase the limits.

CPU being a shared resource is not impactful and can actually help prevent the container layer from inappropriately throttle the ingress controller during reloads which has a number of negative impacts overall.
Memory I can understand as it is a finite resource. However, the normal NGINX behavior of generating a new set of workers for each configuration to allow existing sessions to drain off is what is happening.

**Comment by saedx1** [comment]
> How well does this work for you?
> 
> I am asking because we normally recommend customers simply increase their limits to accommodate the resource spikes that come with reloads. We actually consider it more efficient to increase the limits.
> 
> CPU being a shared resource is not impactful and can actually help prevent the container layer from inappropriately throttle the ingress controller during reloads which has a number of negative impacts overall. Memory I can understand as it is a finite resource. However, the normal NGINX behavior of generating a new set of workers for each configuration to allow existing sessions to drain off is what is happening.

Maybe I'm obsessed with optimality, but should **4 ingress resources + 1 aplogconf** take 2-3 minutes to reload on half a CPU and 800M? This might sound naive, and it might be `nginx` itself that takes most of that time to restart as opposed to the ingress controller templating reloads.

HPA's `behavior` helps us A LOT in the case of reloads where a spike in CPU utilization happens. Instead of triggering the HPA quickly too many times because of that spike, the HPA will need the spike to be sustained for some period and can also be configured to make it scale more conservatively.

The reason the HPA goes up to the max (25 pods in our case) very quickly despite having a very small setup and no traffic is that the reload spike happens, then it causes a small scale-up, then the new pod will have a spike for its config load, which causes a scale up, and so on.

Regardless of all the above, and you may disagree with it, it doesn't hurt to merge the PR. It does not affect the current functionality/behavior; it just gives people more control over the HPA.

**Comment by brianehlert** [comment]
If you are using AppProtect (I am interpreting the aplogconf) and configuring it using YAML Policy objects, the act of applying those policy involves compiling that AppProtect Policy into a binary object which is a CPU intensive process.
I would not expect that to take 2-3 minutes unless the CPU limits are two low and thus the container management system is throttling the ingress controller pod during this compilation, and thus causing the compilation to take longer than it would if the pod was not being throttled.

The guidance we generally provide is to not set CPU limits unless absolutely necessary.  As this causes throttling during CPU spikes when the additional CPU is generally necessary and so that there is not a negative impact on the flow of requests.
In your specific example, our general recommendation has helped a number of customers.

Since CPU allocation in containers is a fair use model as opposed to machines which is generally a processing thread allocation model, CPU spikes are dealt with through throttling and thus reducing the performance of the pod.
It is generally more beneficial to allow and shorten the duration CPU spike and allow the container engine to handle that balance between all pods on the node.

I don't disagree that the PR is not useful.  
I do want to make sure that you have a good experience and tune where it will give you the better result.

Thank you for the additional explanation, that is very helpful to us having a better understanding of your specific use case.

**Comment by jxn** [comment]
> If you are using AppProtect (I am interpreting the aplogconf) and configuring it using YAML Policy objects, the act of applying those policy involves compiling that AppProtect Policy into a binary object which is a CPU intensive process. I would not expect that to take 2-3 minutes unless the CPU limits are two low and thus the container management system is throttling the ingress controller pod during this compilation, and thus causing the compilation to take longer than it would if the pod was not being throttled.
> 
> The guidance we generally provide is to not set CPU limits unless absolutely necessary. As this causes throttling during CPU spikes when the additional CPU is generally necessary and so that there is not a negative impact on the flow of requests. In your specific example, our general recommendation has helped a number of customers.
> 
> Since CPU allocation in containers is a fair use model as opposed to machines which is generally a processing thread allocation model, CPU spikes are dealt with through throttling and thus reducing the performance of the pod. It is generally more beneficial to allow and shorten the duration CPU spike and allow the container engine to handle that balance between all pods on the node.
> 
> I don't disagree that the PR is not useful. I do want to make sure that you have a good experience and tune where it will give you the better result.
> 
> Thank you for the additional explanation, that is very helpful to us having a better understanding of your specific use case.



> If you are using AppProtect (I am interpreting the aplogconf) and configuring it using YAML Policy objects, the act of applying those policy involves compiling that AppProtect Policy into a binary object which is a CPU intensive process. I would not expect that to take 2-3 minutes unless the CPU limits are two low and thus the container management system is throttling the ingress controller pod during this compilation, and thus causing the compilation to take longer than it would if the pod was not being throttled.
> 
> The guidance we generally provide is to not set CPU limits unless absolutely necessary. As this causes throttling during CPU spikes when the additional CPU is generally necessary and so that there is not a negative impact on the flow of requests. In your specific example, our general recommendation has helped a number of customers.
> 
> Since CPU allocation in containers is a fair use model as opposed to machines which is generally a processing thread allocation model, CPU spikes are dealt with through throttling and thus reducing the performance of the pod. It is generally more beneficial to allow and shorten the duration CPU spike and allow the container engine to handle that balance between all pods on the node.
> 
> I don't disagree that the PR is not useful. I do want to make sure that you have a good experience and tune where it will give you the better result.
> 
> The guidance we generally provide is to not set CPU limits unless absolutely necessary. As this causes throttling during CPU spikes when the additional CPU is generally necessary and so that there is not a negative impact on the flow of requests.

I think the problem with not setting the CPU limit is that you cannot get Guaranteed QoS class without setting them.  If you want nginx pods to be the last priority evictions, you simply need to set the cpu limits.  This means that you either must greatly overallocate the limits to account for app protect policy compilation or you have to find a workaround.  I think tweaking the HPA behavior is a valid workaround (at least until there is a workaround for the CPU spikes in app-protect initialization).
