### ISSUE TITLE
Nginx ingress controller can not work as expect

### ISSUE THREAD

**Issue by vantinhuynh** [nginxinc/kubernetes-ingress#470]
**Describe the bug**
I try to deploy my app use Nginx Ingress to public my services out the internet.
My Problem:
My Nginx Ingress controller can not work properly 

**Your environment**
* nginx/nginx-ingress:edge
* Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes platform: AWS (KOPS)
* Using NGINX

**Additional context**
* My yaml file 
[kubernetes copy.zip](https://github.com/nginxinc/kubernetes-ingress/files/2714040/kubernetes.copy.zip)

Expect: 
- access: http://test.tinhuynh.local/app1
- Return: Default page of nginx

The problem: 
- access: http://test.tinhuynh.local/app1
- Return: 404

Note: From Minion I can access to services of my app through IP is ok.

**Comment by pleshakov** [comment]
@vantinhuynh 
Thanks for providing all the manifests.

The problem that you encountered is in fact an expected behavior. When you try to access  http://test.tinhuynh.local/app1, NGINX Ingress Controller proxies that request to one of the app1 pods at `/app1` URI. However, the app1 pod responds with 404 for such a request, because that URI is not configured in the app1 pods.

To fix the problem:
- make sure the app1 pods respond with 200 for `/app1` requests.
- or rewrite the URI in NGINX Ingress Controller by adding the following annotation to the Ingress resource: `nginx.org/rewrites: "serviceName=app1-svc rewrite=/"` This will make NGINX rewrite URI for the app1-svc service. For example, /app1 -> / . See also https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/rewrites
