### ISSUE TITLE
Ingress Class for multiple ingress controller

### ISSUE THREAD

**Issue by mshahbazalam021** [nginxinc/kubernetes-ingress#4702]
**Describe the bug**
I want to use multiple nginx ingress controller in same cluster. Since I have 2 controller the IP keep toggling between both even after defining ingressCalssname annotation in application ingress

This is the controller configmap
apiVersion: v1
data:
  allow-snippet-annotations: "false"
kind: ConfigMap
metadata:
  annotations:
    allow-http: "false"
    allow-snippet-annotations: "true"
    client-body-buffer-size: 16k
    client-body-timeout: "3600"
    client-header-timeout: "3600"
    connection-pool-size: "512"
    force-ssl-redirect: "true"
    ingress-class: nginx-ingress-devops
    keep-alive: "3600"
    keep-alive-requests: "10000"
    keep-alive-timeout: "3600"
    max-worker-connections: "65536"
    meta.helm.sh/release-name: nginx-ingress-devops
    meta.helm.sh/release-namespace: nginx-ingress-devops
    proxy-body-size: "0"
    proxy-buffer-size: 128k
    proxy-buffering: "on"
    proxy-connect-timeout: "3600"
    proxy-read-timeout: "3600"
    proxy-send-timeout: "3600"
    proxy-stream-timeout: "3600"
    send-timeout: "3600"
    ssl-redirect: "true"
    timeout: "3600"
    upstream-keepalive-connections: "900"
    upstream-keepalive-requests: "1000"
    upstream-keepalive-timeout: "3600"
    use-forward-headers: "true"
    use-http2: "true"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress-devops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.9.4
    helm.sh/chart: ingress-nginx-4.8.3
  name: nginx-ingress-devops-ingress-nginx-controller
  namespace: nginx-ingress-devops

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    ngress.kubernetes.io/force-ssl-redirect: "false"
  name: argocd-ingress
  namespace: argocd
spec:
  ingressClassName: nginx-ingress-devops
  rules:
  - host: abc.xyz.com
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - abc.xyz.com
    secretName: argocd

https://docs.nginx.com/nginx-ingress-controller/installation/running-multiple-ingress-controllers/#configuring-ingress-class
https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class

I tried following the above but no clear examples
 
How to define the ingress class resource for namespace
I tried below ingress class resource but it is not working
# ingress-nginx IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx-ingress-devops
spec:
  controller: k8s.io/nginx-ingress-devops-ingress-nginx-controller
  parameters:
    scope: Namespace
    kind: IngressParameter
    name: argocd-devops
    namespace: argocd

**Comment by haywoodsh** [comment]
Thanks for reaching out, @mshahbazalam021.

From your comment, it appears that you might have been deploying a different ingress controller. If your intention is to deploy the NGINX Ingress Controller, I recommend using `controller: nginx.org/ingress-controller` within the Ingress Class definition. You can find an example of this in the following link: https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/common/ingress-class.yaml 

Instead of using the config map, it would be more suitable to use the command line argument`-ingress-class` during the Ingress Controller deployment. You can find more details on this in the NGINX Ingress Controller documentation here https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/#-ingress-class-string. 

This approach allows you to define which ingress controller instance should manage a specific Ingress object. Additionally, if you need each ingress controller to watch resources in specific namespaces, consider the command line argument `-watch-namespace` as documented in https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/#-watch-namespace-string
