### ISSUE TITLE
Nginx Plus Dashboard Access

### ISSUE THREAD

**Issue by srikantheee84** [nginxinc/kubernetes-ingress#545]
Is it possible to view nginx plus dashboard without port forwarding ? Like http://<host_ip>:<host_port>/dashboard.html ? Currently, if I do port forwarding it works whereas without that I’m getting access denied. I’m able to see request reaching nginx pod and returning 403 in the logs. Can you please explain ? Thanks!

**Comment by srikantheee84** [comment]
Ideally, we would like to add VIP with host_ip and host_port as a pool members and outside client will access through those VIP’s.

**Comment by pleshakov** [comment]
@srikantheee84 
Please take a look at the `-nginx-status-allow-cidrs` [cli argument](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/cli-arguments.md), which whitelists IPv4 IP/CIDR blocks to allow access to NGINX stub_status or the NGINX Plus API. By default, it allows only `127.0.0.1`, which works only for port forwarding. 

Note that the Ingress Controller with NGINX Plus is covered by the NGINX Plus support contract so that if you prefer, you can open Ingress Controller support tickets with our support team.

**Comment by srikantheee84** [comment]
Yes. We are already working with Roman Schachter on this. Thanks!
