### ISSUE TITLE
avoid overwriting tagged dockerhub images

### ISSUE THREAD

**Issue by rawlingsj** [nginxinc/kubernetes-ingress#56]
It looks like recent fixes have been released and replaced the 0.3 tag in dockerhub yesterday https://hub.docker.com/r/nginxdemos/nginx-ingress/tags/ which has broken some logic we have in the fabric8 project.  Would it be possible to not replace tagged versions, perhaps push changes to a latest tag?

**Comment by pleshakov** [comment]
Thanks for reporting. We will introduce the DockerHub image versioning of every code change, instead of only the versioning of major changes. 
The image with the  latest version of the controller -- https://github.com/nginxinc/kubernetes-ingress/commit/e320d5c2a3fd7c6037241de95c5299752dcdc9c9 -- is pushed with `0.3.1` tag. The previous version -- https://github.com/nginxinc/kubernetes-ingress/commit/34bd21178915c3c533afaeb7cb8d8ebf511b18ac -- which you had before, is available via the `0.3` tag.

**Comment by rawlingsj** [comment]
ok thanks @pleshakov!  We're just mid release to will test shortly.  Thanks!

**Comment by pleshakov** [comment]
@rawlingsj We added version information to the controllers -- https://github.com/nginxinc/kubernetes-ingress/pull/58

Now when the controller starts it logs its version. The version is set during the build process.
Also each version gets a corresponding tag on DockerHub and a tag on the master brach -- https://github.com/nginxinc/kubernetes-ingress/tags.

Note that the mentioned in my previous message `0.3.1` version doesn't exist in the changelog, but there is the Docker tag `0.3.1` with the controller from the https://github.com/nginxinc/kubernetes-ingress/commit/e320d5c2a3fd7c6037241de95c5299752dcdc9c9 commit.

From now on we won't be pushing updates to the tags that already exist on DockerHub, except the `latest` one. With each change we will create a new version.

**Comment by rawlingsj** [comment]
@pleshakov that sounds great!  Thanks for that.
