### ISSUE TITLE
Help Wanted: Not hitting ingress on port 80 and 443

### ISSUE THREAD

**Issue by christianriosa** [nginxinc/kubernetes-ingress#618]
Hi, Good day guys. hope you can help me on this.

I have the following setup on a EC2 instance.
I installed nginxinc controller then manually set the external IP by adding these lines below on the controller.

spec:
  clusterIP: 10.107.157.210
  externalIPs:
    - 13.X.X.X

![image](https://user-images.githubusercontent.com/50305143/60868431-98c2b200-a25f-11e9-91ca-9ea3654b2bf3.png)

Then I followed the instructions on deploying a sample app on:
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example
and I can see that the external IP on the ingress resource

![image](https://user-images.githubusercontent.com/50305143/60868572-ef2ff080-a25f-11e9-8e4b-ec75097a1fca.png)

but my problem is I can't seem to access the sample apps.
I got "unable to connect" error in browser and connection refused on port 80 when I try to curl.

i'm not seeing any logs when i'm accessing it. seems like i'm not hitting the ingress resource.

**To Reproduce**
1. Installed using helm chart
2. set external IP manually
3. followed instruction on how to install/access sample app:
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example

**Expected behavior**
reply from the apps and related logs on the ingress controller

**Your environment**
* Version of the Ingress Controller - nginx/nginx-ingress:1.5.1
* Version of Kubernetes - version 1.15
* Kubernetes platform - AWS EC2
* Using NGINX

**Comment by Dean-Coakley** [comment]
Hi @christianriosa 

Sorry to hear you are experiencing issues.

For aws ec2 we have some specific install instructions in order to make the ingress controller function correctly. They are documented here - https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#42-service-with-the-type-loadbalancer 

Can you verify that you have the required annotations, etc, documented there?

**Comment by Dean-Coakley** [comment]
> * set external IP manually

Can you fully clarify how you did that?

Is your cluster capable of provisioning LoadBalancer services?

**Comment by christianriosa** [comment]
Hello Dean,
Thank you for working on this. 

I set the external IP by adding this couple of lines under spec.
externalIPs:
    - 13.X.X.X
![image](https://user-images.githubusercontent.com/50305143/60931082-ecc6a880-a2ea-11e9-9c37-d5a716215f05.png)


My understanding on the link you've provided is we need to pay for ELB service?
is there a way for us not do that so that we are also not tied to a cloud vendor?
 link https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#42-service-with-the-type-loadbalancer

**Comment by pleshakov** [comment]
@christianriosa 
the recommended way to expose the Ingress Controller pods in the cloud is through a service with the type LoadBalancer. On AWS, it will be either ELB or NLB, on other clouds -- the corresponding cloud load balancers. An allocated cloud load balancer will provide a stable external endpoint (IP address) and a layer of HA for the Ingress Controller pods.

Other options applicable are a NodePort service and a service with External IPs. Please find the documentation regarding all Service-related options here -- https://kubernetes.io/docs/concepts/services-networking/service/ Since you're trying to use the ExternalIPs options - see https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

Another option for exposing the IC pods is to deploy the IC as a DeamonSet with port mapping enabled.  This way NGINX ports are mapped directly to the ports of Kubernetes nodes, and clients can send requests to the IC using the public IPs of the nodes where the IC pods are running. To deploy the IC as a DeamonSet that, configure the `controller.kind` parameter to the value `daemonset`  of the Helm chart.

**Comment by christianriosa** [comment]
Hello @pleshakov,

Thank you very much for your recommendation. We will follow the 1st one which is to use ELB.
Hoping that you can guide us on this.

I've followed the link provided by @Dean-Coakley.
 at step 4.2 
I need to add these on the configmap
proxy-protocol: "True"
real-ip-header: "proxy_protocol"
set-real-ip-from: "0.0.0.0/0"

here is the screenshot of the current configmap
![image](https://user-images.githubusercontent.com/50305143/61037931-a2365080-a3fe-11e9-98ce-d03592d52ee7.png)


next step is to describe the nginx service.
I don't see anything related to our ELB or public ip on the output.
![image](https://user-images.githubusercontent.com/50305143/61038792-3654e780-a400-11e9-8f6c-57ca97d82a00.png)


BTW.. what we did is create a ELB manually then relate that to our EC2 instance I'm not sure if ELB should be created automatically when I do step 4.2

**Comment by pleshakov** [comment]
@christianriosa 
your Kubernetes cluster should be able to provision ELBs automatically for every service with the type LoadBalancer that you deploy. It looks like it is not the case for your cluster. Could you possibly double check that your cluster was correctly configured for running on AWS?

**Comment by christianriosa** [comment]
Hello @pleshakov @Dean-Coakley .

As I understand it, its a requirement to get a cloud loadbalancer when exposing services/apps on K8 while hosted on the cloud. I'm still figuring out why my cluster was not able to auto create ELBs. I will now close the ticket. Thank you very much for the help.
