### ISSUE TITLE
Please update Deployment API Version

### ISSUE THREAD

**Issue by bframke** [nginxinc/kubernetes-ingress#747]
The current supplied APIVersion of the Deployment file for NGinx is deprecated and won't work with Kubernetes 1.16 and up. Please change it from extensions/v1beta1 to apps/v1.

If you use more Deployment files, also change it there too.

**Comment by Dean-Coakley** [comment]
Hi @bframke 

We decided to not update the ingress controller `1.5` manifests to the new api as `1.6` is expected very shortly.

In the meantime you can:
* Use the `edge` version instead. The api version has been updated there already.
* Edit the deployments yourself.

Otherwise: 1.6 will be available very soon.

Sorry for the inconvenience.

**Comment by bframke** [comment]
Okay, thanks for the information.

**Comment by Dean-Coakley** [comment]
@bframke 

The 1.6 release was delayed due to circumstances outside of our control. I pushed a new `v1.5.8` release which includes Kubernetes 1.16 support.

Enjoy! :)

**Comment by bframke** [comment]
Ouh nice, thanks for the information :D Will try it out later.
