### ISSUE TITLE
Limit the number of connections with nginx.org/max-conns

### ISSUE THREAD

**Issue by rere16** [nginxinc/kubernetes-ingress#793]
Hi,

My Kubernetes cluster uses a replicaSet to run N similar pods. Each pod can only handle one websocket connection du to resource limitations.
I have created a Nginx ingress using the annotation "nginx.org/max-conns=1" to limit the number of connections to 1 for each pod. This works properly except when I scale up/down the number of pods. It seems that the state of nginx ingress is reseted, nginx then accepts a new connection on each pod and does not take into account the number of existing connections before scaling up/down (Two connections on the same pod are then possible).

I would like to know if there is a configuration to avoid this behavior ?

Thanks

**Comment by pleshakov** [comment]
@rere16 
My apologies for the late reply!

Each scale up/scale down event of the backends pod makes the Ingress Controller generate a new configuration and reload NGINX. As a result, a new generation of NGINX worker processes is launched and ready to accept new connections while the old generation  continues to serve any established connections until they are closed by clients/backends. The generations have independent counters of the number of connections and  that's why you observe that behavior. 

With NGINX, there is no good workaround to avoid that behavior. As a workaround, you can make NGINX terminate the existing established connections when doing a reload. For that, you can configure `worker-shutdown-timeout` to `0` [ConfigMap key](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#general-customization)  . But this is probably not acceptable, because all established connections will be terminated. 

With NGINX Plus, the scale up/ down events will not lead to a configuration reload (the Ingress Controller will update NGINX Plus via its API), so this problem will not happen after scale up/down events. However, all other changes such as changes to Ingress resources, secrets, ConfigMap, etc., will cause a configuration reload - so you will still observe the same behavior but less frequently.

**Comment by rere16** [comment]
@pleshakov Thank you very much for your reply.
