### ISSUE TITLE
Ingress with a backend service type ExternalName documentation needs to be updated

### ISSUE THREAD

**Issue by bzon** [nginxinc/kubernetes-ingress#837]
The doc https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/externalname-services  states that:

```
Note: This feature is only available in NGINX Plus.
```

We had a use-case for this and I just tried it and it worked just fine. I'm also not sure how it can be an NGINX Plus feature only. Can someone clarify this?

Thanks!

**Comment by Rulox** [comment]
Hi @bzon this is a good question.

Similar question was asked when we got asked for this feature in the past. Please refer to this comment for more [information](https://github.com/nginxinc/kubernetes-ingress/issues/262#issuecomment-376918311).

Technically, with NGINX open source you can get something similar yes, but it will have some issues (that might cause disruptions in your IC). As per that comment, NGINX will try to resolve that DNS in every reload, keep in mind, we reload NGINX any time there's a change in an Ingress Resource (configmap, configs, annotations, etc), scale up-down of services using those Ingresses, etc... if only one of those times the DNS can't be resolved, NGINX will fail to reload, and an old config will be present in your IC.

Additionally, any change to the DNS won't be noticed by NGINX until next reload.

These 2 caveats make the usage with NGINX open source not fully supported, that's why we make use of the NGINX Plus features to resolve the addresses in realtime, and also keep using all the upstream features as any other service.

Does it make sense to you?

**Comment by bzon** [comment]
Thanks for the clarification. What I’ve done is something like this https://github.com/nginxinc/kubernetes-ingress/issues/262#issuecomment-454418636

So ExternalNames do work but with caveats or proceed with caution. I think it must still be documented?

**Comment by Rulox** [comment]
Yeah that's a "workaround" for it.

The thing is, we don't want to support a feature that is not fully functional, we could add that to the docs but I am not sure we'd like to offer a "buggy" incomplete feature. Anyways happy to discuss this internally with the team.

a FYI: If you use our CRDs of VS/VSR, I think that feature is disabled for Open Source (Ingress Controller won't even generate a proper NGINX config)

Thanks!
