### ISSUE TITLE
Error Creating TemplateExecutor: open nginx-plus.tmpl 

### ISSUE THREAD

**Issue by ksummersill2** [nginxinc/kubernetes-ingress#928]
I have tried multiple ways of following the instructions to build an NGINX-Plus docker image for the NGINX-Ingress controller. Nothing has worked. 
I started to build with Windows and saw that the main.go file is not set up for absolute paths. So I fixed that and still received the error about not finding the nginx-plus.tmpl template. 
Then I tried to build with an Ubuntu machine. I received the same results. 

`I0419 16:01:19.014312       1 main.go:169] Starting NGINX Ingress controller Version=1.6.3 GitCommit=b504012b
F0419 16:01:19.015665       1 main.go:234] Error creating TemplateExecutor: open nginx-plus.tmpl: no such file or directory`

To reproduce, follow the instructions on NGINX Site: https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/

**Comment by Rulox** [comment]
Hi @ksummersill2 I am sorry you haven't been able to build the image.

As I can see you are using NGINX Plus. This error is because the image is being built with the wrong Dockerfile. Please make sure you use the `DockerfileForPlus` when building the Ingress Controller image. The [step 3 ](https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/#building-the-image-and-pushing-it-to-the-private-registry)of the docs has 2 main sections, one for NGINX and other for NGINX Plus.  Note how, in your case, the `DOCKERFILE` variable should be set to `DockerfileForPlus`.

The possible Dockerfiles are specified in the docs [here](https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/#makefile-variables).

Let me know if it makes sense, thanks!

PS: If this doesn't work, can you let me know what command are you using to build the image? Thanks

**Comment by ksummersill** [comment]
I used the DockerfileForPlus by specifying it as make argument, but still get the error. 
`make DOCKERFILE=DockerfileForPlus`

**Comment by ksummersill2** [comment]
@Rulox I talked to @pleshakov. He said that I was getting the errors because I am using windows. He recommended using 1.7. So I am going to try to pull the 1.7 release from the repo and build the image with my NGINX-Plus keys.
