### ISSUE TITLE
Support for Logging to Syslog

### ISSUE THREAD

**Issue by saggiyogesh** [nginxinc/kubernetes-ingress#955]
**Is your feature request related to a problem? Please describe.**
With docker Nginx, we are forwarding access logs to a UDP service, but same not exists on the ingress helm chart. 

**Describe the solution you'd like**
An option in the helm chart and nginx.tmpl to enable the logging to Syslog

**Comment by Rulox** [comment]
Hi @saggiyogesh 

Thanks for the proposal, we'll study it and get back to you.

The way logs works right now is that NGINX logs are sent to the process with PID 1 (in this case, the Ingress Controller process). Check [this](https://github.com/nginxinc/kubernetes-ingress/blob/master/build/Dockerfile#L7). For this reason, I believe allowing NGINX logs to be sent to an  UDP service won't be enough (we need to send Ingress Controller logs as well, because they provide useful information for the user).

In the meantime, can't you send the container logs to your log system using [Kubernetes](https://kubernetes.io/docs/concepts/cluster-administration/logging/)?

**Comment by pleshakov** [comment]
Hi @saggiyogesh 

> With docker Nginx, we are forwarding access logs to a UDP service, but same not exists on the ingress helm chart.

What is your NGINX configuration for that?

For the Ingress Controller, one approach for supporting syslog is to modify the generated NGINX config, so that includes the syslog configuration. That could be accomplished with the following methods:
* `http-snippets` ConfigMap key -- https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates
* Custom templates. Take a look at https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/custom-templates/

For helm, both the snippets and custom templates are configured via `controller.config.entries` parameter.

**Comment by saggiyogesh** [comment]
Hi @pleshakov 
Thanks for these snippets & templates, I missed them. I will use this for Syslog logs forwarding. 
As of now I forked the repo and changed directly in nginx.tmpl.
