### ISSUE TITLE
grpc http2_max_requests

### ISSUE THREAD

**Issue by DanSalomon** [nginxinc/kubernetes-ingress#970]
Hi,

 I've seen some errors related to connection, such as RST_STREAM 7 in my system from client gong from outside into the K*S throw the ingress 
i am using GRPC in my system so all of my services exposing GRPC endpoint , after some   
Reading a bit about the error in HTTP/2 RFC it is mentioned and explained, max requests per connection have reached and the connection is now resetting.
setting this parameter 'http2-max-requests' higher in nginx reduces the errors but eventually ill reach the number of requests...
the client gets the error and should retry.

it would be nice if the a new channel would have been created automatically by nginx or if there was no limit in http2 on the number of requests

**Comment by pleshakov** [comment]
Hi @DanSalomon 

While the Ingress Controller deals with NGINX configuration, we don't have deep expertise in a lot of NGINX topics. Because of that, I recommend taking a look at the following resources specific to NGINX, and, perhaps getting some advice there:
* https://trac.nginx.org/nginx/ - for bug reports, feature requests
* http://mailman.nginx.org/mailman/listinfo/nginx - community mailing list
