### ISSUE TITLE
could not get nginx-ingress/default-server-secret

### ISSUE THREAD

**Issue by MrLiuFang** [nginxinc/kubernetes-ingress#986]
**Describe the bug**
As my English is not very good, try to describe my problems
ingress controller logs : Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get "https://10.10.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret": dial tcp 10.10.0.1:443: i/o timeout

**To Reproduce**
1. According to official deployment documents
     [https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/](url)
     Clone version of kupernetes-ingress-v1.7.1 
     *Execute the following commands in turn*
```
     kubectl apply -f common/ns-and-sa.yaml
     kubectl apply -f rbac/rbac.yaml
     kubectl apply -f common/default-server-secret.yaml
     kubectl apply -f common/nginx-config.yaml
     kubectl apply -f common/vs-definition.yaml
     kubectl apply -f common/vsr-definition.yaml
     kubectl apply -f common/ts-definition.yaml
     kubectl apply -f common/gc-definition.yaml
     kubectl apply -f common/global-configuration.yaml
     kubectl apply -f deployment/nginx-ingress.yaml
```
2. kubectl logs nginx-ingress-6c8cb6c694-mpdbv -n nginx-ingress
 ```
I0608 12:55:28.408468       1 main.go:186] Starting NGINX Ingress controller Version=1.7.0 GitCommit=d2ad33c4
F0608 12:55:58.411190       1 main.go:298] Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get "https://10.10.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret": dial tcp 10.10.0.1:443: i/o timeout
```
3. kubectl get service
 ```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.10.0.1    <none>        443/TCP   3d6h
 ```
4. kubectl describe service kubernetes
 ```
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.10.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         172.16.30.135:6443
Session Affinity:  None
Events:            <none>
 ```
5. ipvsadm -Ln
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.10.0.1:443 rr
  -> 172.16.30.135:6443           Masq    1      1          0         
TCP  10.10.0.10:53 rr
  -> 10.122.0.18:53               Masq    1      0          0         
  -> 10.122.0.19:53               Masq    1      0          0         
TCP  10.10.0.10:9153 rr
  -> 10.122.0.18:9153             Masq    1      0          0         
  -> 10.122.0.19:9153             Masq    1      0          0         
TCP  10.10.216.252:8080 rr
  -> 10.122.1.32:8080             Masq    1      0          0         
  -> 10.122.1.33:8080             Masq    1      0          0         
UDP  10.10.0.10:53 rr
  -> 10.122.0.18:53               Masq    1      0          0         
  -> 10.122.0.19:53               Masq    1      0          0         
```
6. kubectl get secret -n nginx-ingress
```
default-server-secret       Opaque                                2      2d4h
default-token-zbfk4         kubernetes.io/service-account-token   3      2d4h
nginx-ingress-token-c7f8h   kubernetes.io/service-account-token   3      2d4h
```
7. kubectl describe secret default-server-secret -n nginx-ingress
```
Name:         default-server-secret
Namespace:    nginx-ingress
Labels:       <none>
Annotations:  
Type:         Opaque

Data
====
tls.crt:  1013 bytes
tls.key:  1679 bytes
```
8. kubectl init
```
kubeadm init --kubernetes-version 1.18.2  \
--apiserver-advertise-address 172.16.30.135   \
--image-repository registry.aliyuncs.com/google_containers  \
--service-cidr 10.10.0.0/16 --pod-network-cidr 10.122.0.0/16
```

**environment**
* Version of the Ingress Controller - v1.7.1
* Version of Kubernetes - 1.18.2
* Kubernetes platform - kubeadm
* Version of docker - 19.03.11
* Using NGINX 
* Version of CentOS - 8.1.1911

**I hope I can get your help**
**thank you**

**Comment by Rulox** [comment]
Hi @MrLiuFang 

Are you using Calico or any other network tool in your k8s cluster? This problem happens when the pod of the Ingress Controller can't access to the [Kubernetes API.](https://kubernetes.io/docs/reference/using-api/api-overview/)

Check [this comment](https://github.com/nginxinc/kubernetes-ingress/issues/911#issuecomment-610321571) (and issue) where someone had this problem before. Following those steps you can check if the pod has access to the API or not. If it doesn't, check your network configuration to make sure the Pod where the Ingress Controller is running has access to the Kubernetes API. This is a requirement for the Ingress Controller to work.

Let me know if this makes sense

Thanks

**Comment by MrLiuFang** [comment]
Hi @Rulox 
Thank you for your help. With calico installed, the ingress controller runs successfully

**Comment by Rulox** [comment]
@MrLiuFang Just a heads up, Calico is not needed to run the Ingress Controller. You should be able to deploy and run the Ingress Controller without Calico (or any other network addon).

I just asked if you were using Calico or any other networking tool in order to understand better your problem.

**Comment by victory7** [comment]
I have exactly the same issue and checked weave-net, calico and flannel CNIs.
All of my flannel pods are running and basically don't seem that I have a network problem.
But Nginx ingrees controller (both daemon-set and deployment) get an error and restarts every 15-20 seconds.
The error in describe pod is:
`Back-off restarting failed container`

And in pod logs:
`Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get "https://10.96.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret": dial tcp 10.96.0.1:443: i/o timeout`

I use:
CentOS 8
Docker 19.03.11
K8S 1.18.4
Nginx ingress 1.7.1

**Comment by MrLiuFang** [comment]
@victory7 
When I only use flannel, the connection timeout will occur. When I uninstall flannel, I only install calico, and ingress is running normally. I guess it's because flannel doesn't have network policy function that makes pod unable to connect to k8s service。

It is recommended that you only try using calico

**Comment by victory7** [comment]
I guess the issue is because I have multiple network interfaces and something goes wrong in creating cluster or pod network.
I've switched to calico once again and still no chance. I have an external network with 192.168.0.0/16 range so I changed the pod-network-cidr in kubeadm init and CALICO_IPV4_CIDR in calico manifest to range 10.244.0.0/16 and calico is running well and two pods of that are running but API call timeout issue is still there.

**Comment by Rulox** [comment]
@victory7 the only "networking" requirement for the Ingress Controller to work is that the pod must have access to the k8s API, without this access, the Ingress Controller is useless, that's why the pod fails on start. Is there any way you can check how to provide the KIC pod access to the k8s api in your infrastructure?

I am afraid I can't really help you with this because this is an issue that depends on how your infra/network is configured 🤔  I haven't used Calico before, but I assume they should have a way to grant pods access to the k8s API, otherwise, not only ours, but any Ingress Controller or K8S Operator will work in your cluster.

**Comment by victory7** [comment]
My problem solved using tigera-operator for installing calico cni.
Thanks at all
