### ISSUE TITLE
[question] Recommended way to handle relative links

### ISSUE THREAD

**Issue by oscarlofwenhamn** [nginxinc/kubernetes-ingress#998]
I am facing a scenario where I want to set up two services behind the same Ingress, using sub-paths to route between the two - one at `/` and one at `/sub-site`.

This works insofar as initial routing, but as soon as any internal routing happens the `URL/sub-site/foo` routes to `URL/foo`, my guess because of relative links. 
I had an idea of handling this using a `proxy_redirect` and `sub_filter`, but can't seem to figure out a way to add it to only one of the generated `location` blocks, and since it's a `/ -> /sub-site` redirection I really don't want it to be added to both locations. 

One option could be to add separate Ingress objects for the two, and still add the `proxy_redirect` and `sub_filter`, but my hope is to find a way to deal with it in the same Ingress object.

What is the recommended way of handling relative links, and is there any way of dealing with my scenario using only one Ingress?

**Comment by pleshakov** [comment]
Hi @oscarlofwenhamn 

> One option could be to add separate Ingress objects for the two, and still add the proxy_redirect and sub_filter

this would be a recommended approach.

Another alternative is to write [custom annotation(s)](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/custom-annotations/) for that. As a parameter, you can specify the Ingress path you want to apply it. However, this approach is more involved, because it requires changing the template.

**Comment by oscarlofwenhamn** [comment]
Great, thank you. Question answered, closing.
